### ISSUE TITLE
Increase allowed length of log message details

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/hermes#42]
Currently, the max length of the details of a log message that the server allows is 1024. Could we increase this to 16384? I will not use this very often, but want to send the full traceback of Pytest when an upgrade fails, and that can be longer than 1024 characters.

@empicano is this bad for the database?

**Comment by empicano** [comment]
> is this bad for the database?

In general, yes, fewer data is usually better/faster, but what counts is the system providing valuable insights 😋 I'm also not 100% happy with how the MQTT messages are validated at the moment, with HTTP requests I like to validate them very strictly (no parsing/casting like what `pydantic` does), in order to avoid ambiguity, but with MQTT you don't get the same feedback when something fails validation.

In the future, I'd like to be more lenient with the MQTT validation. One option I was thinking of was accepting oversized `details` but cutting them off after some character limit before writing them to the database. We can also definitely set the character limit higher, I'll just have to see how fast our database fills up, and maybe set the retention for logs lower than the current 120 days.

For context, at the moment, I'm estimating our dataset to be ~75GB after 2 years, so space will be scarce, but I'll have a look into compression in the next weeks, which should hopefully help.
